### ISSUE TITLE
Request: If there is no album, can it move to the next one?

### ISSUE THREAD

**Issue by Prohibitive** [Sorrow446/Napster-Downloader#1]
Hello,
Can you make the wrong albums in the attached and automatically created list go to the next download instead of the error below?
So I can automatically download the whole archive.
[List.txt](https://github.com/Sorrow446/Napster-Downloader/files/9095593/List.txt)
Error: 
C:\Users\Administrator\Downloads\napster>np_dl_x64.exe list.txt -f 5

Album 1 of 23695:
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.main()
        G:/go/napster_lossless/main.go:701 +0xe0e

@Sorrow446 
Sorry my english is bad.
Regards

**Comment by Sorrow446** [comment]
https://anonfiles.com/F84cn4xdyc/np_dl_x64_exe

**Comment by Prohibitive** [comment]
thank you @Sorrow446 
Maybe Added Artist download full albums etc..
Sample: qobuz-dl
