### ISSUE TITLE
Error: Failed to get album metadata.

### ISSUE THREAD

**Issue by Manute1337** [Sorrow446/Napster-Downloader#11]
Hello,

on the both Albums linked below i always get the error:
Failed to get album metadata.
parsing time "\"\"" as "\"2006-01-02T15:04:05Z07:00\"": cannot parse "\"" as "2006"

https://web.napster.com/album/alb.7583903
https://web.napster.com/album/alb.253965723

Tried also with play.napster.com

Same error in cmd-line or in txt-file.

Anyway, thank you for the great work and cool tool! Downloaded a few weeks ago some tracks with success :), and other are still working.

Happy holidays!

**Comment by Sorrow446** [comment]
Already fixed a while back. The binaries are outdated.
https://github.com/Sorrow446/Napster-Downloader/commit/0c59733eb01ac1588cf5de5add906bd9776d4701

**Comment by Manute1337** [comment]
Sorry, did look only for updates on the bins. Will try to compile :-). Thanks for the fast and nice reply.

**Comment by Sorrow446** [comment]
No probs. Sorry for outdated bins, I sometimes don't bother as it's pretty easy to compile yourself.
