### ISSUE TITLE
Corrupted AAC tracks.

### ISSUE THREAD

**Issue by Sorrow446** [Sorrow446/Napster-Downloader#2]
My tagger doesn't play well with AAC tracks from Napster. The Atom tree looks fine, so not sure on the cause.

**Comment by thefarmboy25** [comment]
The issue might be in writing the tags. I downloaded an album in 192 AAC and all the tracks were corrupt and wouldn't play besides one where it failed to write the tags, that song works fine. Re-downloading the song where the tags wrote successfully corrupted the song. Maybe disable tags for AAC tracks and see if that fixes the problem?

**Comment by Sorrow446** [comment]
The tag writing is the problem. There's something weird about Napster's AACs I can't figure out.

**Comment by Sorrow446** [comment]
Plan to fix soon, know the problem.

**Comment by damarges** [comment]
> Plan to fix soon, know the problem.

any plans when this could be fixed?

**Comment by Sorrow446** [comment]
I wrote my own MP4 (AAC) tagger for it, but https://github.com/Sorrow446/go-mp4tag/issues/9 might be a problem for Napster's tracks. I don't remember if they have those boxes. I'll try implementing it today, but it's been trouble.

**Comment by Sorrow446** [comment]
Fixed. https://github.com/Sorrow446/Napster-Downloader/commit/9b4562b470f8a344d66ef0aae6dd1309d0182909
